### ISSUE TITLE
日報登録機能 STEP1: snippets テーブルにだけデータを保存する

### ISSUE THREAD

**Issue by ittyi** [bob-g12/dayrepo-for-transportation#22]
## 完了の定義
- PRがマージされている
  - 日報入力画面に、登録ボタンを設置する
  - フォーム画面より、データを入力後保存のボタンを押したら、snippets テーブルにデータが保存される

- 画面設計: https://docs.google.com/presentation/d/1igetkEL3_GuhN0Juzms8qkPuOY31M_YYfwdgyRiLeRs/edit#slide=id.g2b64928ff50_1_25

### 作業の見積もり
  - 具体的に何を行うか？
  - 具体的にどこのファイルをどう編集するか？
  - それらの作業に何時間くらいかかりそうか？
  - いつまでに終わらせられそうか？
  - 上記を一回考えSlackなどに投げ、実際に完了したタイミングでギャップを振り返る。

- タスクの細分化(タスクの分割)を行ってみてください。イメージがわかなければ、とりあえず以下のようにやってみてください。
 ### 一気に全ての機能や見た目を完成させるのではなく、スモールステップで日々確実に進捗を出せるようにしましょう。
注) 以下ですらまだ結構抽象度が高いです。可能であれば、もっともっと小さくできるとほぼ確実に進捗が出せるようになります。※例として、何々が表示される、フォームのこのカラムだけ保存できる、DBにアクセスがまずできるか確認する、ルーティングだけ設定し、APIをリクエストしたら hello worldする、一旦単なるテキスト入力のフォームにして、データや入力の仕方を便利にするJSの修正はそれぞれのフォームごとにタスクを分ける、など。
   - [ ] まずはCSSはなしでhtmlのフォームのみ設置する
   - [ ] htmlフォームの入力をAPIで取得しターミナルに出力だけできるようにする
   - [ ] APIで取得後DBに保存してみる
   - [ ] 保存したものが一覧画面で参照できるかを確認する
   - [ ] 見た目をと整える
   - など。見た目が先でもいいです。
 - 上記の一つ一つが終わったごとに、ここのissueにスクショコメントを残して上記にチェックをつける、やコミットをする。などをすると後から振り返りやすくてよりいいかも？

**Comment by bob-g12** [comment]
# 見積もり
> 具体的に何を行うか？

簡易的な投稿画面の作成
投稿機能の作成
- 具体的にどこのファイルをどう編集するか？

htmlファイルを作成
viwesにclassを作成
formsファイルの作成
- それらの作業に何時間くらいかかりそうか？

1. htmlファイルを作成
簡易的な表示　30分
2. viwesの処理を作成
登録動作の作成　1時間
3. formsファイルの作成
htmlファイルで表示するフォームの設定　1時間

**Comment by bob-g12** [comment]
nullでエラーになる際の処理を作成する(予定)
