### ISSUE TITLE
Excel出力機能の技術調査

### ISSUE THREAD

**Issue by ittyi** [bob-g12/dayrepo-for-transportation#35]
## 概要
- ペルソナである企業様に使うにあたり、事務の方に最終的にExcel形式で出力していただく必要がある。
- 日報周辺のデータをどうやれば Excel の形式に変換できるか？を調べる

## (恐らく)ポイント
- 既に会社で利用されている Excel ファイルを入手したい
- Excel ファイルがどんな構成でできているのかを理解する
- 楽なライブラリがないかを探す(Python、JS)
- 実装ロジックや方針を考える

### このチケットも事前に見積もりは行ってください。
- やり方は以前の issue と同じです

**Comment by bob-g12** [comment]
# 見積もりの見積もり
## 目的
- 実装方法が不明確で、実装工程が想定できないため見積もりのための調査をする
## 調査対象
- djangoからExcelへのデータの受け渡し方法
- そのためのファイル構成などの大まかなやり方
## 調査時間
- どうExcelにデータを渡すか、本題は見つけ決定する。-3時間-
- そのやり方-1時間+本題で浮いた時間-
