### ISSUE TITLE
日報一覧画面を簡易的に完成させる。

### ISSUE THREAD

**Issue by ittyi** [bob-g12/dayrepo-for-transportation#9]
## 以下が終わるまでBlock
https://github.com/bob-g12/dayrepo-for-transportation/issues/6

## 完了の定義
- PRがマージされている
  - テストデータをいくつか作成すると、一覧画面に表示される

- 画面設計: https://docs.google.com/presentation/d/1igetkEL3_GuhN0Juzms8qkPuOY31M_YYfwdgyRiLeRs/edit#slide=id.g2b641228934_1_170

## やってみてほしいこと
- 作業の見積もり
  - 具体的に何を行うか？
  - 具体的にどこのファイルをどう編集するか？
  - それらの作業に何時間くらいかかりそうか？
  - いつまでに終わらせられそうか？
  - 上記を一回考えSlackなどに投げ、実際に完了したタイミングでギャップを振り返る。

**Comment by bob-g12** [comment]
# 見積もり
> 具体的に何を行うか？
簡易的な表示画面の作成
> 具体的にどこのファイルをどう編集するか？
htmlファイルを作成
> それらの作業に何時間くらいかかりそうか？
永く見て日曜(3日)

**Comment by bob-g12** [comment]
すごく簡素ですが、日報データの表示画面を作りました。
![image](https://github.com/bob-g12/dayrepo-for-transportation/assets/126374166/5eb98f49-73db-4f05-806c-50cd55825f8e)
